version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-bJvD_6AiyptwTjEzx7_G
      - TZ=${TIMEZONE}
      - ADVERTISE_IP=http://10.0.0.53:32400/
    volumes:
      - ./plex/config:/config
      - ./plex/media:/media
      - ./plex/transcode:/transcode
      - ./sonarr/tv:/tv
      - ./radarr/movies:/movies
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${USERNAME}
      - PASS=${PASSWORD}
      - WHITELIST= 10.0.0.*, *.*.*.*
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ./transmission/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TIMEZONE}
    volumes:
      - ./readarr/config:/config
      - ./readarr/books:/books #optional
      - ${DOWNLOAD_DIR}:/downloads # this should match Transmissions download folder
    ports:
      - 8787:8787
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=022
      - TZ=${TIMEZONE}
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv #optional
      - ${DOWNLOAD_DIR}:/downloads # this should match Transmissions download folder
    ports:
      - 8989:8989
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./calibre/confog:/config
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
  # sites:
  #   image: app
  #   container_name: sites
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports: 
  #     - 8080:8080
  #   volumes: 
  #     - ./sites:/usr/share/nginx/html
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies #optional
      - ${DOWNLOAD_DIR}/complete:/downloads/complete # this should match Transmissions download folder
    ports:
      - 7878:7878
    restart: unless-stopped
  samba:  
    image: dperson/samba  
    container_name: samba  
    ports:  
      - "137:137/udp"  
      - "138:138/udp"  
      - "139:139/tcp"  
      - "445:445/tcp"  
    restart: unless-stopped  
    healthcheck:  
      disable: true  
    environment:  
      - TZ=${TIMEZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - WORKGROUP=workgroup  
      - USER=${USERNAME};${PASSWORD}  
      - RECYCLE=false  
      - PERMISSIONS=true
      - SHARE=Media;/media;yes;no;no;;${USERNAME}  
    volumes:  
      - ./:/media
