version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-bJvD_6AiyptwTjEzx7_G
      - TZ='mountain'
      - ADVERTISE_IP=http://your_host_ip:32400/
    volumes:
      - ./plex/config:/config
      - ./plex/media:/media
      - ./plex/transcode:/transcode
      - ./transmission/media:/transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=tristanhampton
      - PASS=Localphone1
      - WHITELIST= 10.0.0.*, *.*.*.*
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ./transmission/config:/config
      - ./transmission/media:/media/TV\ Shows
      - ./transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Canada/Edmonton
    volumes:
      - ./readarr/config:/config
      - ./readarr/books:/books #optional
      - ./transmission/media:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Canada/Edmonton
    volumes:
      - ./sonarr/config:/config
      - ./sonarr/tv:/tv #optional
      - ./sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ./calibre/config:/config
    ports:
      - 8081:8081
    restart: unless-stopped
  sites:
    image: app
    container_name: sites
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8080:8080
    volumes: 
      - ./sites:/usr/share/nginx/html
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Edmonton
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ./jackett/config:/config
      - ./jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Canada/Edmonton
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies #optional
      - ./radarr/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - fpm=false #optional
    volumes:
      - ./organizr/config:/config
    ports:
      - 7979:7979
