version: "3"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - PLEX_CLAIM=claim-bJvD_6AiyptwTjEzx7_G
      - TZ='mountain'
      - ADVERTISE_IP=http://your_host_ip:32400/
    volumes:
      - ~/plex/config:/config
      - ~/plex/media:/media
      - ~/plex/transcode:/transcode
      - ~/../../transmission/downloads/complete:/transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=tristanhampton
      - PASS=Localphone1
      - WHITELIST= 10.0.0.*, *.*.*.*
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /path/to/data:/config
      - ~/plex/media:/downloads/Movies
      - /transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    user: 1000
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Canada/Edmonton
    volumes:
      - ~/Compose/readarr/data:/config
      - ~/Compose/readarr/books:/books #optional
      - /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
      - TZ=Canada/Edmonton
    volumes:
      - ~/Compose/sonarr/data:/config
      - ~/Compose/sonarr/tv:/tv #optional
      - ~/Compose/sonarr/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD= #optional
      - CLI_ARGS= #optional
    volumes:
      - ~/Compose/calibre/data:/config
    ports:
      - 8081:8081
    restart: unless-stopped
  sites:
    image: app
    container_name: sites
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8080:8080
    volumes: 
      - ./sites:/usr/share/nginx/html